-- Per-service / per-app CPU-RAM (Console UI → deploy manifest)

ALTER TABLE project_services
  ADD COLUMN IF NOT EXISTS resources_mode TEXT NOT NULL DEFAULT 'platform',
  ADD COLUMN IF NOT EXISTS cpu_request TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS memory_request TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cpu_limit TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS memory_limit TEXT NOT NULL DEFAULT '';

ALTER TABLE project_repos
  ADD COLUMN IF NOT EXISTS resources_mode TEXT NOT NULL DEFAULT 'platform',
  ADD COLUMN IF NOT EXISTS cpu_request TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS memory_request TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cpu_limit TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS memory_limit TEXT NOT NULL DEFAULT '';
