replicas: 1

ingress:
  enabled: true
  ingressClassName: nginx
  extraAnnotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  tls:
    source: secret
    secretName: tls-rancher-ingress

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

# RKE2 đã có PSP/security — tắt PSP legacy của Rancher
global:
  cattle:
    psp:
      enabled: false
